### ISSUE TITLE
12GB VRAM getting OOM with Q8_0, but not in Forge.

### ISSUE THREAD

**Issue by caustiq** [city96/ComfyUI-GGUF#18]
Able to use Forge with default settings to run the Q8_0 variant on a 3060 w 12GB VRAM and 32GB sys RAM.

But with this node in Comfy I always get OOM trying to load the models up for inference. Tried --lowvram mode too.

**Comment by city96** [comment]
Just pushed a patch that should fix this. Please test it!

**Comment by NHLOCAL** [comment]
I also had the same problem with lowvram, now the problem is solved with the update push!

**Comment by city96** [comment]
Those log messages can be safely ignored.

**Comment by caustiq** [comment]
Nice one man.

**Comment by caustiq** [comment]
I did get an OOM after about 20-30 gens of smooth sailing. 
I turned off Xorg and ran headless to free up a little more cause I was at 94-96% VRAM usage.
But it seems like Comfy will just use even more if it can, so still riding close to the edge.
Dunno if it's related to your changes so just thought I'd report that one OOM.
